services:
  postgres:
    container_name: mentorship
    image: 'postgres:latest'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /data/postgres
    ports:
      - "5444:5432"

    restart: always

volumes:
  db:
