services:
  postgres:
    container_name: mentorship
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: mentorship-tracker
      POSTGRES_PASSWORD: mawuli302
      POSTGRES_USER: mawuli
      PGDATA: /data/postgres
    ports:
      - "5444:5432"

    restart: always

volumes:
  db:
